require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '18.0'
install! 'cocoapods', :deterministic_uuids => false

target 'HelloWorld' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  flags[:fabric_enabled] = false
  flags[:new_arch_enabled] = false

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,   # disable Hermes for now to avoid deployment-target conflict
    :fabric_enabled => false,
    :new_arch_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'HelloWorldTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Disable Folly coroutines so the missing header isn't needed
    installer.pods_project.targets
      .select { |t| t.name == 'RCT-Folly' }
      .each   { |t| t.build_configurations.each do |c|
        c.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'FOLLY_HAS_COROUTINES=0']
      end }
  end
end
